.TH "CommonInterface" 3 "Thu Mar 22 2018" "SRec Walker Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCommon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommon\fP ($debug)"
.br
.ti -1c
.RI "\fBconnect\fP ($db)"
.br
.ti -1c
.RI "\fBexecuteQuery\fP ($sql, $filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Created by PhpStorm\&. User: JonathanWesterfield Date: 2/8/18 Time: 4:31 PM 
.PP
Definition at line 11 of file CommonInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCommon\fP ( $debug)"

.PP
Implemented in \fBCommon\fP\&.
.SS "connect ( $db)"

.PP
Implemented in \fBCommon\fP\&.
.SS "executeQuery ( $sql,  $filename)"

.PP
Implemented in \fBCommon\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SRec Walker Counter from the source code\&.
