.TH "Counter" 3 "Thu Mar 22 2018" "SRec Walker Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Counter \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBinsert\fP (cnx, cursor, inOrOut)"
.br
.ti -1c
.RI "def \fBdbConnect\fP ()"
.br
.ti -1c
.RI "def \fBsignal_handler\fP (sig, frame)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBboard\fP = PyMata('COM3', verbose=True)"
.br
.ti -1c
.RI "\fBdata\fP = board\&.get_sonar_data()"
.br
.ti -1c
.RI "\fBdistance1\fP = \fBdata\fP[12][1]"
.br
.ti -1c
.RI "\fBdistance2\fP = \fBdata\fP[13][1]"
.br
.ti -1c
.RI "int \fBhit1\fP = 0"
.br
.ti -1c
.RI "int \fBhit2\fP = 0"
.br
.ti -1c
.RI "int \fBdist\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Counter\&.dbConnect ()"

.PP
.nf
Connects to the database using my credentials and the mysql password. Will print out a string
depeding on the status of the connection i.e.: whether if failed or not and why.
:return:

.fi
.PP
 
.PP
Definition at line 40 of file Counter\&.py\&.
.SS "def Counter\&.insert ( cnx,  cursor,  inOrOut)"

.PP
.nf
This function inserts an entry into the database. Will insert the location (should be the Student Recreation Center
but can be changed), a boolean value as to whether the subject exited or entered, the day of the week in number
format (using the mysql dayofweek(now()) function) and a DateTime stamp (using mysql now() function)
:param cnx:
:param cursor:
:param inOrOut:
:return: Boolean

.fi
.PP
 
.PP
Definition at line 13 of file Counter\&.py\&.
.SS "def Counter\&.signal_handler ( sig,  frame)"

.PP
Definition at line 78 of file Counter\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "board = PyMata('COM3', verbose=True)"

.PP
Definition at line 75 of file Counter\&.py\&.
.SS "data = board\&.get_sonar_data()"

.PP
Definition at line 96 of file Counter\&.py\&.
.SS "int dist = 0"

.PP
Definition at line 114 of file Counter\&.py\&.
.SS "distance1 = \fBdata\fP[12][1]"

.PP
Definition at line 98 of file Counter\&.py\&.
.SS "distance2 = \fBdata\fP[13][1]"

.PP
Definition at line 99 of file Counter\&.py\&.
.SS "int hit1 = 0"

.PP
Definition at line 100 of file Counter\&.py\&.
.SS "int hit2 = 0"

.PP
Definition at line 101 of file Counter\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SRec Walker Counter from the source code\&.
