.TH "Users/JonathanWesterfield/Documents/CSCE 315/RecWalkerCounter/Python2.7/Counter.py" 3 "Thu Mar 22 2018" "SRec Walker Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Users/JonathanWesterfield/Documents/CSCE 315/RecWalkerCounter/Python2.7/Counter.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCounter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBinsert\fP (cnx, cursor, inOrOut)"
.br
.ti -1c
.RI "def \fBdbConnect\fP ()"
.br
.ti -1c
.RI "def \fBsignal_handler\fP (sig, frame)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBboard\fP = PyMata('COM3', verbose=True)"
.br
.ti -1c
.RI "\fBdata\fP = board\&.get_sonar_data()"
.br
.ti -1c
.RI "\fBdistance1\fP = data[12][1]"
.br
.ti -1c
.RI "\fBdistance2\fP = data[13][1]"
.br
.ti -1c
.RI "int \fBhit1\fP = 0"
.br
.ti -1c
.RI "int \fBhit2\fP = 0"
.br
.ti -1c
.RI "int \fBdist\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SRec Walker Counter from the source code\&.
