.TH "md__users__jonathan_westerfield__documents__c_s_c_e_315__rec_walker_counter__r_e_a_d_m_e" 3 "Thu Mar 22 2018" "SRec Walker Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__users__jonathan_westerfield__documents__c_s_c_e_315__rec_walker_counter__r_e_a_d_m_e \- RecWalkerCounter 
Personal Repo for developing the Database API for this class project
.PP
I'm doing this because I accidently deleted my old Database API
.PP
.SH "How to Use"
.PP
.PP
The important file is the \fBDBInterface\fP file but all of the files except for the \fBtest\&.php\fP file are required\&. Run the \fBtest\&.php\fP file to see the output of the \fBDBInterface\&.php\fP file\&.
.PP
.SH "Needed Work"
.PP
.PP
Once verified, I will go in and delete all of the print statements from the functions since they won't be needed when the API is being used\&. 
