.TH "PDBAPI" 3 "Thu Mar 22 2018" "SRec Walker Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PDBAPI \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fB__del__\fP (self)"
.br
.ti -1c
.RI "def \fBinsert\fP (self, inOrOut)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file PDBAPI\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self)"

.PP
Definition at line 13 of file PDBAPI\&.py\&.
.SS "def __del__ ( self)"

.PP
Definition at line 28 of file PDBAPI\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def insert ( self,  inOrOut)"

.PP
Definition at line 33 of file PDBAPI\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SRec Walker Counter from the source code\&.
