.TH "stats.php" 3 "Thu Mar 22 2018" "SRec Walker Counter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stats.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdisplay_stats\fP ($date_format, $sub_division, $data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$thisCommon\fP = new \fBCommon\fP(true)"
.br
.ti -1c
.RI "\fB$db\fP = new \fBDBAPI\fP($thisCommon)"
.br
.ti -1c
.RI "if(!isset($_GET['mode'])) elseif(strtolower($_GET['mode'])== 'day'||strtolower($_GET['mode'])== 'month'||strtolower($_GET['mode'])== 'year') \fBelse\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "display_stats ( $date_format,  $sub_division,  $data)"

.PP
Definition at line 8 of file stats\&.php\&.
.SH "Variable Documentation"
.PP 
.SS "$db = new \fBDBAPI\fP($thisCommon)"

.PP
Definition at line 6 of file stats\&.php\&.
.SS "$thisCommon = new \fBCommon\fP(true)"

.PP
Definition at line 5 of file stats\&.php\&.
.SS "if (!isset($_GET['mode'])) elseif (strtolower($_GET['mode'])== 'day'||strtolower($_GET['mode'])== 'month'||strtolower($_GET['mode'])== 'year') else"
\fBInitial value:\fP
.PP
.nf
{
    echo '<script>console\&.log("Could not load form with mode \\"' \&. $_GET['mode'] \&. '\\"\&.");</script>'
.fi
.PP
Definition at line 48 of file stats\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SRec Walker Counter from the source code\&.
